CREATE TABLE [dbo].[BackupReport]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY, 
    [Success] BIT NOT NULL, 
    [Message] NVARCHAR(MAX) NOT NULL, 
    [InstanceId] INT NOT NULL, 
    [BeginDate] DATETIME2 NOT NULL, 
    [EndDate] DATETIME2 NOT NULL, 
    [AddedFiles] INT NOT NULL, 
    [SizeOfAddedFiles] BIGINT NOT NULL, 
    [ExaminedFiles] INT NOT NULL, 
    [SizeOfExaminedFiles] BIGINT NOT NULL, 
    [NotProcessedFiles] INT NOT NULL, 
    [DurationTicks] BIGINT NOT NULL, 
    [DeletedFiles] INT NOT NULL, 
    [ModifiedFiles] INT NOT NULL, 
    [DeletedFolders] INT NOT NULL, 
    [OpenedFiles] INT NOT NULL, 
    [SizeOfModifiedFiles] BIGINT NOT NULL, 
    [SizeOfOpenedFiles] BIGINT NOT NULL, 
    [AddedFolders] INT NOT NULL, 
    [TooLargeFiles] INT NOT NULL, 
    [FilesWithError] INT NOT NULL, 
    [ModifiedFolders] INT NOT NULL, 
    [ModifiedSymlinks] INT NOT NULL, 
    [AddedSymlinks] INT NOT NULL, 
    [PartialBackup] BIT NOT NULL, 
    [DryRun] BIT NOT NULL, 
    [VerboseOutput] BIT NOT NULL, 
    [VerboseErrors] BIT NOT NULL, 
    [Warnings] NVARCHAR(MAX) NOT NULL, 
    [Errors] NVARCHAR(MAX) NOT NULL, 
    CONSTRAINT [FK_BackupReport_ToInstance] FOREIGN KEY ([InstanceId]) REFERENCES [Instance]([Id])
)
