/*
Deployment script for BackupMonitor

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "BackupMonitor"
:setvar DefaultFilePrefix "BackupMonitor"
:setvar DefaultDataPath "c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "c:\Program Files\Microsoft SQL Server\MSSQL11.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET ANSI_NULLS ON,
                ANSI_PADDING ON,
                ANSI_WARNINGS ON,
                ARITHABORT ON,
                CONCAT_NULL_YIELDS_NULL ON,
                QUOTED_IDENTIFIER ON,
                ANSI_NULL_DEFAULT ON,
                CURSOR_DEFAULT LOCAL,
                RECOVERY FULL 
            WITH ROLLBACK IMMEDIATE;
    END


GO
IF EXISTS (SELECT 1
           FROM   [master].[dbo].[sysdatabases]
           WHERE  [name] = N'$(DatabaseName)')
    BEGIN
        ALTER DATABASE [$(DatabaseName)]
            SET PAGE_VERIFY NONE 
            WITH ROLLBACK IMMEDIATE;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Rename refactoring operation with key 91465a3d-04ae-45e3-be60-14e66bf17f1d is skipped, element [dbo].[Instance].[IP] (SqlSimpleColumn) will not be renamed to Url';


GO
PRINT N'Rename refactoring operation with key ba41e995-6616-4612-a9b7-5de1ed0e324d is skipped, element [dbo].[BackupReport].[Duration] (SqlSimpleColumn) will not be renamed to DurationTicks';


GO
PRINT N'Creating [dbo].[BackupReport]...';


GO
CREATE TABLE [dbo].[BackupReport] (
    [Id]                  INT            IDENTITY (1, 1) NOT NULL,
    [Success]             BIT            NOT NULL,
    [Message]             NVARCHAR (MAX) NOT NULL,
    [InstanceId]          INT            NOT NULL,
    [BeginDate]           DATETIME2 (7)  NOT NULL,
    [EndDate]             DATETIME2 (7)  NOT NULL,
    [AddedFiles]          INT            NOT NULL,
    [SizeOfAddedFiles]    INT            NOT NULL,
    [ExaminedFiles]       INT            NOT NULL,
    [SizeOfExaminedFiles] INT            NOT NULL,
    [NotProcessedFiles]   INT            NOT NULL,
    [DurationTicks]       BIGINT         NOT NULL,
    [DeletedFiles]        INT            NOT NULL,
    [ModifiedFiles]       INT            NOT NULL,
    [DeletedFolders]      INT            NOT NULL,
    [OpenedFiles]         INT            NOT NULL,
    [SizeOfModifiedFiles] INT            NOT NULL,
    [SizeOfOpenedFiles]   INT            NOT NULL,
    [AddedFolders]        INT            NOT NULL,
    [TooLargeFiles]       INT            NOT NULL,
    [FilesWithError]      INT            NOT NULL,
    [ModifiedFolders]     INT            NOT NULL,
    [ModifiedSymlinks]    INT            NOT NULL,
    [AddedSymlinks]       INT            NOT NULL,
    [PartialBackup]       BIT            NOT NULL,
    [DryRun]              BIT            NOT NULL,
    [VerboseOutput]       BIT            NOT NULL,
    [VerboseErrors]       BIT            NOT NULL,
    [Warnings]            NVARCHAR (MAX) NOT NULL,
    [Errors]              NVARCHAR (MAX) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[Instance]...';


GO
CREATE TABLE [dbo].[Instance] (
    [Id]   INT            IDENTITY (1, 1) NOT NULL,
    [Name] NVARCHAR (250) NOT NULL,
    [Url]  NVARCHAR (250) NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);


GO
PRINT N'Creating [dbo].[FK_BackupReport_ToInstance]...';


GO
ALTER TABLE [dbo].[BackupReport] WITH NOCHECK
    ADD CONSTRAINT [FK_BackupReport_ToInstance] FOREIGN KEY ([InstanceId]) REFERENCES [dbo].[Instance] ([Id]);


GO
-- Refactoring step to update target server with deployed transaction logs

IF OBJECT_ID(N'dbo.__RefactorLog') IS NULL
BEGIN
    CREATE TABLE [dbo].[__RefactorLog] (OperationKey UNIQUEIDENTIFIER NOT NULL PRIMARY KEY)
    EXEC sp_addextendedproperty N'microsoft_database_tools_support', N'refactoring log', N'schema', N'dbo', N'table', N'__RefactorLog'
END
GO
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = '91465a3d-04ae-45e3-be60-14e66bf17f1d')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('91465a3d-04ae-45e3-be60-14e66bf17f1d')
IF NOT EXISTS (SELECT OperationKey FROM [dbo].[__RefactorLog] WHERE OperationKey = 'ba41e995-6616-4612-a9b7-5de1ed0e324d')
INSERT INTO [dbo].[__RefactorLog] (OperationKey) values ('ba41e995-6616-4612-a9b7-5de1ed0e324d')

GO

GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[BackupReport] WITH CHECK CHECK CONSTRAINT [FK_BackupReport_ToInstance];


GO
PRINT N'Update complete.';


GO
